### ISSUE TITLE
Revive the project

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/naggum#20]
- [x] update to the latest F# / .NET
- [x] convert Readme to Markdown format
- [x] move License to a single file
- [x] add Editorconfig
- [x] use packages from Nuget instead of storing the binaries in the source repository
- [x] determine [Andivionian project status](https://github.com/ForNeVeR/andivionian-status-classifier)
- [x] add Appveyor automatic building / testing

Yup, that's official. I am starting it again!

And I've decided to base the current development on the older naggum-1 code instead of the newest DLR experiments.
